lang: 
  - fr
  - en

tags: 
  - graphic
  - animation
  - motion
  - game
  - web
  - app

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
collections:
  en:
    relative_directory: en
  fr:
    relative_directory: fr
